/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState, useMemo } from "react";
import moment from "moment";
import {
  LuPlus,
  LuSearch,
  LuFolder,
  LuBrain,
  LuTarget,
  LuSparkles,
  LuX,
  LuLayers,
} from "react-icons/lu";
import { toast } from "react-hot-toast";
import DashboardLayout from "../../components/layouts/DashboardLayout";
import { useNavigate } from "react-router-dom";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import SummaryCards from "../../components/cards/SummaryCards";
import Modal from "../../components/Modal";
import CreateSessionForms from "./CreateSessionForms";
import DeleteAlertContent from "../../components/DeleteAlertContent";

const FILTER_TAGS = ["All", "Frontend", "Backend", "Full Stack", "System Design", "DevOps"];

const Dashboard = () => {
  const navigate = useNavigate();

  const [sessions, setSessions] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTag, setSelectedTag] = useState("All");
  const [openCreateModal, setOpenCreateModal] = useState(false);
  const [openDeleteAlert, setOpenDeleteAlert] = useState({
    open: false,
    data: null,
  });

  // Fetching all sessions
  const fetchAllSessions = async () => {
    try {
      const response = await axiosInstance.get(API_PATHS.SESSION.GET_ALL);
      setSessions(response.data || []);
    } catch (error) {
      console.error("Error fetching session data: ", error);
      toast.error("Failed to load interview sessions.");
    }
  };

  useEffect(() => {
    let isMounted = true;
    if (isMounted) {
      fetchAllSessions();
    }
    return () => {
      isMounted = false;
    };
  }, []);

  const deleteSession = async (sessionData) => {
    try {
      await axiosInstance.delete(API_PATHS.SESSION.DELETE(sessionData?._id));
      toast.success("Session deleted successfully.");
      setOpenDeleteAlert({
        open: false,
        data: null,
      });
      fetchAllSessions();
    } catch (error) {
      console.error("Error deleting session data:", error);
      toast.error("Failed to delete session.");
    }
  };

  // Filtered sessions based on search & category chip
  const filteredSessions = useMemo(() => {
    return sessions.filter((s) => {
      const matchesSearch =
        searchQuery.trim() === "" ||
        s?.role?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        s?.topicsToFocus?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        s?.description?.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesTag =
        selectedTag === "All" ||
        s?.role?.toLowerCase().includes(selectedTag.toLowerCase()) ||
        s?.topicsToFocus?.toLowerCase().includes(selectedTag.toLowerCase());

      return matchesSearch && matchesTag;
    });
  }, [sessions, searchQuery, selectedTag]);

  // Aggregate Metrics
  const totalQuestions = useMemo(() => {
    return sessions.reduce((acc, curr) => {
      return acc + (Array.isArray(curr?.questions) ? curr.questions.length : 0);
    }, 0);
  }, [sessions]);

  const uniqueTopicsCount = useMemo(() => {
    const set = new Set();
    sessions.forEach((s) => {
      if (s?.topicsToFocus) {
        s.topicsToFocus.split(",").forEach((t) => set.add(t.trim().toLowerCase()));
      }
    });
    return set.size;
  }, [sessions]);

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Top Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-200/80">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">
              Interview Command Center
            </h1>
            <p className="text-sm text-slate-500 mt-1">
              Track, practice, and master role-specific technical questions generated by AI.
            </p>
          </div>

          <button
            className="inline-flex items-center justify-center gap-2 bg-slate-900 hover:bg-indigo-600 text-white text-sm font-semibold px-5 py-2.5 rounded-xl shadow-xs transition-colors cursor-pointer shrink-0"
            onClick={() => setOpenCreateModal(true)}
          >
            <LuPlus className="text-lg" />
            <span>Create Session</span>
          </button>
        </div>

        {/* Quick Metrics Bar */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 my-6">
          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center text-lg shrink-0">
              <LuFolder />
            </div>
            <div>
              <p className="text-xs font-medium text-slate-500">Total Sessions</p>
              <h3 className="text-xl font-bold text-slate-900">{sessions.length}</h3>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center text-lg shrink-0">
              <LuBrain />
            </div>
            <div>
              <p className="text-xs font-medium text-slate-500">Questions Bank</p>
              <h3 className="text-xl font-bold text-slate-900">{totalQuestions}</h3>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center text-lg shrink-0">
              <LuLayers />
            </div>
            <div>
              <p className="text-xs font-medium text-slate-500">Focus Topics</p>
              <h3 className="text-xl font-bold text-slate-900">{uniqueTopicsCount}</h3>
            </div>
          </div>

          <div className="bg-white p-4 sm:p-5 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center text-lg shrink-0">
              <LuTarget />
            </div>
            <div>
              <p className="text-xs font-medium text-slate-500">Readiness Score</p>
              <h3 className="text-xl font-bold text-slate-900">
                {sessions.length > 0 ? `${Math.min(100, sessions.length * 15 + 25)}%` : "0%"}
              </h3>
            </div>
          </div>
        </div>

        {/* Search & Filter Controls */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div className="relative flex-1 max-w-md">
            <LuSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 text-sm" />
            <input
              type="text"
              placeholder="Search by role, topics, or description..."
              className="w-full bg-white text-sm text-slate-800 placeholder-slate-400 pl-10 pr-9 py-2.5 rounded-xl border border-slate-200 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 transition-all shadow-xs"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            {searchQuery && (
              <button
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                onClick={() => setSearchQuery("")}
              >
                <LuX className="text-sm" />
              </button>
            )}
          </div>

          {/* Filter Chips */}
          <div className="flex items-center gap-2 overflow-x-auto pb-2 md:pb-0 custom-scrollbar">
            {FILTER_TAGS.map((tag) => (
              <button
                key={tag}
                className={`text-xs font-medium px-3.5 py-1.5 rounded-xl whitespace-nowrap transition-all cursor-pointer ${
                  selectedTag === tag
                    ? "bg-slate-900 text-white shadow-xs"
                    : "bg-white text-slate-600 border border-slate-200 hover:border-slate-300 hover:bg-slate-50"
                }`}
                onClick={() => setSelectedTag(tag)}
              >
                {tag}
              </button>
            ))}
          </div>
        </div>

        {/* Sessions Grid / Empty State */}
        {filteredSessions.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {filteredSessions.map((data) => (
              <SummaryCards
                key={data._id}
                role={data?.role || ""}
                topicsToFocus={data?.topicsToFocus || ""}
                experience={data?.experience || ""}
                questions={
                  Array.isArray(data?.questions) ? data.questions.length : 0
                }
                description={data?.description || ""}
                lastUpdated={
                  data?.updatedAt
                    ? moment(data.updatedAt).format("Do MMM YYYY")
                    : ""
                }
                onSelect={() => navigate(`/interview-prep/${data._id}`)}
                onDelete={() => setOpenDeleteAlert({ open: true, data })}
              />
            ))}
          </div>
        ) : (
          <div className="bg-white rounded-3xl border border-slate-200/80 p-8 sm:p-12 text-center max-w-xl mx-auto my-8 shadow-xs">
            <div className="w-16 h-16 rounded-2xl bg-indigo-50 text-indigo-600 flex items-center justify-center text-3xl mx-auto mb-4">
              <LuSparkles />
            </div>
            <h3 className="text-lg font-bold text-slate-900 mb-1">
              {sessions.length === 0
                ? "No interview sessions yet"
                : "No matching sessions found"}
            </h3>
            <p className="text-sm text-slate-500 mb-6 max-w-md mx-auto">
              {sessions.length === 0
                ? "Create your first AI-tailored session to practice realistic technical questions and review in-depth concept explanations."
                : "We couldn't find any sessions matching your filter or search query. Try clearing your filters."}
            </p>
            {sessions.length === 0 ? (
              <button
                className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold px-6 py-2.5 rounded-xl shadow-xs transition-colors cursor-pointer"
                onClick={() => setOpenCreateModal(true)}
              >
                <LuPlus className="text-lg" />
                <span>Create Your First Session</span>
              </button>
            ) : (
              <button
                className="text-xs font-semibold text-indigo-600 hover:underline cursor-pointer"
                onClick={() => {
                  setSearchQuery("");
                  setSelectedTag("All");
                }}
              >
                Reset Search & Filters
              </button>
            )}
          </div>
        )}

        {/* Floating Action Button (Mobile View) */}
        <button
          className="sm:hidden fixed bottom-6 right-6 z-30 w-12 h-12 rounded-full bg-slate-900 text-white flex items-center justify-center shadow-lg shadow-slate-900/25 cursor-pointer hover:bg-indigo-600 transition-colors"
          onClick={() => setOpenCreateModal(true)}
          aria-label="Create Session"
        >
          <LuPlus className="text-2xl" />
        </button>
      </div>

      {/* Create Session Modal */}
      <Modal
        isOpen={openCreateModal}
        onClose={() => setOpenCreateModal(false)}
        hideHeader
      >
        <div className="w-full max-w-lg mx-auto">
          <CreateSessionForms onClose={() => setOpenCreateModal(false)} />
        </div>
      </Modal>

      {/* Delete Alert Modal */}
      <Modal
        isOpen={openDeleteAlert?.open}
        onClose={() => setOpenDeleteAlert({ open: false, data: null })}
        title="Delete Session"
      >
        <div className="w-full max-w-md mx-auto">
          <DeleteAlertContent
            content="Are you sure you want to delete this interview session? This action cannot be undone."
            onDelete={() => deleteSession(openDeleteAlert.data)}
            onClose={() => setOpenDeleteAlert({ open: false, data: null })}
          />
        </div>
      </Modal>
    </DashboardLayout>
  );
};

export default Dashboard;
